import Link from "next/link";
export const metadata = {
  title: "Scoring",
  description: "Generated by create next app",
};

const getData = async () => {
  const res = await fetch("http://localhost:3000/api/schedule");
  const data = await res.json();
  return data;
};

export default async function layout({ children, params }) {
  const scheules = await getData();
  const schedule = scheules.data.filter((sdl) => sdl.id == params.id);
  const { teamNameVs, vsTeamName, tossWinTeam, chooseTo, matchNo } =
    schedule[0];
  return (
    <html className="bg-gray-400" lang="en">
      <body className="m-3">
        <div className="mb-4">
          <nav className="sm:w-[80%] w-[100%] ">
            <ul className="flex sm:w-[20%] w-[70%] space-x-16 m-auto text-center">
              <li>
                <Link href={`/scooring/${params.id}`}>LIVE</Link>
              </li>
              <li>
                <Link href={`/scooring/${params.id}/scorcut`}>Scorcut</Link>
              </li>
              <li>
                <Link href={`/scooring/${params.id}/info`}>Info</Link>
              </li>
              <li>
                <Link href={`/`}>Home</Link>
              </li>
            </ul>
          </nav>
          <div className="text-center text-2xl mt-5 font-bold mb-2">
            <h1>
              {teamNameVs} <span className="text-red-500">VS</span> {vsTeamName}
            </h1>
          </div>
          <hr />
        </div>
        {children}
      </body>
    </html>
  );
}
