import Link from "next/link";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-gray-400" lang="en">
      <body>
        {/* main manu bar from bellow */}
        <div className="sm:w-[50%] w-[80%] m-auto bg-slate-300 p-4 rounded my-2">
          <div className="flex w-[80%] m-auto ">
            <div className="flex-1">
              <Link href={"/add/addTeam"}>Add Team</Link>
            </div>
            <div className="flex-1">
              <Link href={"/add/addPlayer"}>Add Player</Link>
            </div>
            <div className="flex-1">
              <Link href={"/add/addSchedule"}>Add Schedule</Link>
            </div>
            <div className="flex-1">
              <Link href={"/add/addSeries"}>Add Series</Link>
            </div>
          </div>
        </div>
        {children}
      </body>
    </html>
  );
}
