import Link from "next/link";
import ".././app/globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-gray-400" lang="en">
      <body>
        <div>
          <nav className="sm:w-[80%] w-[100%] ">
            <ul className="flex w-[60%] sm:w-[20%] space-x-16 m-auto text-center">
              <li>
                <Link href="/">Home</Link>
              </li>
              <li>
                <Link href="/schedule">Schedule</Link>
              </li>
              <li>
                <Link href="/teams">Teams</Link>
              </li>
            </ul>
          </nav>
        </div>
        {children}
      </body>
    </html>
  );
}
