import Link from "next/link";
import ".././app/globals.css";
import MainNave from "@/components/MainNave";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html className="bg-gray-400" lang="en">
      <body>
        <div className="main">
          <MainNave />
        </div>
        {children}
      </body>
    </html>
  );
}
